import { Zone, Equipment, Batch, Material, BOMEntry, ProcessStage, TransferGate, Order } from '@/types/erp';

// ============================================================
// ZONES — Real facility layout from URS
// 50L: ~3m × 2m, ≥3.5m ceiling | 500L: ~4m × 3m, ≥5m ceiling
// ============================================================

export const zones: Zone[] = [
  {
    id: 'zone-a-upstream',
    name: 'Zone A — Upstream Fermentation',
    type: 'upstream',
    area: 6,
    isoClass: 'ISO 8 (Class 100,000)',
    temperature: '25–40°C',
    description: 'Seed culture through production bioreactor. 380V/50Hz/3Φ, 2-3 bar steam, PW/WFI',
    x: 20,
    y: 20,
    width: 380,
    height: 200,
  },
  {
    id: 'zone-b-downstream',
    name: 'Zone B — Downstream Processing',
    type: 'downstream',
    area: 6,
    isoClass: 'ISO 8',
    temperature: '4°C (harvest)',
    description: 'Centrifugation, spray drying, freeze drying',
    x: 420,
    y: 20,
    width: 280,
    height: 200,
  },
  {
    id: 'zone-c-formulation',
    name: 'Zone C — Formulation & Packaging',
    type: 'formulation',
    area: 12,
    isoClass: 'ISO 8',
    temperature: '20–25°C',
    description: 'Mixing, homogenization, filling, sealing, labeling',
    x: 720,
    y: 20,
    width: 360,
    height: 200,
  },
  {
    id: 'zone-d-qc',
    name: 'Zone D — QC Laboratory',
    type: 'qc',
    area: 12,
    description: 'Micro (spore count), HPLC, bioassay (LC₅₀), media QC',
    x: 20,
    y: 260,
    width: 340,
    height: 160,
  },
  {
    id: 'zone-e-warehouse',
    name: 'Zone E — Warehouse',
    type: 'warehouse',
    area: 15,
    temperature: '4–8°C (cold)',
    description: 'Cold storage, dry storage, dispatch — GCC/MENA',
    x: 380,
    y: 260,
    width: 340,
    height: 160,
  },
  {
    id: 'zone-f-utilities',
    name: 'Zone F — Utilities',
    type: 'utilities',
    area: 15,
    description: 'Electric boiler (2-3 bar, 100-500 kg/h), chiller, oil-free compressor (6-8 bar), PW/WFI system',
    x: 740,
    y: 260,
    width: 340,
    height: 160,
  },
];

// ============================================================
// EQUIPMENT — Real specs from URS + vendor pricing
// ============================================================

export const equipment: Equipment[] = [
  // Upstream
  {
    id: 'eq-seed-br',
    name: 'Seed Bioreactor',
    category: 'upstream',
    zoneId: 'zone-a-upstream',
    specs: {
      volume: '2–5L',
      material: 'Glass',
      sterilization: 'Autoclavable',
      rpm: '300',
      temp: '30°C',
      impellers: '3× (1/3 vessel diameter)',
    },
    vendor: 'Eppendorf / Infors HT',
    costRange: '$5K–$15K',
    status: 'running',
    hoursRunning: 1240,
    efficiency: 94,
  },
  {
    id: 'eq-prod-br-50',
    name: '50L Production Bioreactor',
    category: 'upstream',
    zoneId: 'zone-a-upstream',
    specs: {
      volume: '50L working (80L total, 62.5% fill)',
      material: 'SS316L',
      surfaceFinish: '0.8 Ra (ext), 0.4 Ra (int)',
      sterilization: 'SIP (130°C, 2-3 bar)',
      agitation: '100–800 rpm, 3× Rushton impellers',
      aeration: 'Air 0.5–2.0 VVM, O₂ 0–0.5 VVM',
      temp: '25–40°C (±0.5°C)',
      pH: '6.5–7.5 (±0.1)',
      DO: '≥30% sat (±5%)',
      probes: 'pH×2 (Ingold 25mm), DO×2 (optical), Temp×1 (Pt100)',
      ports: 'Addition×6, Sampling×4, Probe×8',
      CIP: 'Yes (spray ball)',
      offGas: 'O₂ 0-25%, CO₂ 0-10%',
      MFC: 'Yes',
      maxPressure: '2.5 bar relief',
      antifoam: 'Conductivity sensor + automated peristaltic dosing',
    },
    vendor: 'Lab1st BR500-M1',
    costRange: '$39K–$43.6K',
    status: 'running',
    lastMaintenance: '2026-04-10',
    nextMaintenance: '2026-07-10',
    hoursRunning: 3480,
    efficiency: 91,
  },
  {
    id: 'eq-prod-br-500',
    name: '500L Production Bioreactor',
    category: 'upstream',
    zoneId: 'zone-a-upstream',
    specs: {
      volume: '500L working',
      material: 'SS316L',
      sterilization: 'SIP',
      agitation: '100–800 rpm, 3× impellers',
      note: 'Geometric similarity to 50L required (constant D/T, H/D)',
      scaleUp: 'Constant kLa strategy',
      floorSpace: '4m × 3m',
      ceilingHeight: '≥5m',
    },
    vendor: 'Lab1st / Eppendorf / Sartorius',
    costRange: '$50K–$150K',
    status: 'idle',
    hoursRunning: 890,
    efficiency: 96,
  },
  {
    id: 'eq-media-prep',
    name: 'Media Preparation Tank',
    category: 'upstream',
    zoneId: 'zone-a-upstream',
    specs: { volume: '100L', type: 'Jacketed', agitation: 'Yes', water: 'PW or WFI', sterilization: 'Autoclave or in-line' },
    vendor: 'Chinese vendors',
    costRange: '$5K–$10K',
    status: 'running',
    hoursRunning: 2100,
    efficiency: 98,
  },
  {
    id: 'eq-autoclave',
    name: 'Autoclave',
    category: 'upstream',
    zoneId: 'zone-a-upstream',
    specs: { volume: '100L', cycle: '121°C, 20min' },
    vendor: 'Tuttnauer',
    costRange: '$5K–$15K',
    status: 'idle',
    hoursRunning: 1560,
    efficiency: 99,
  },
  // Downstream
  {
    id: 'eq-centrifuge',
    name: 'Disc Stack Centrifuge',
    category: 'downstream',
    zoneId: 'zone-b-downstream',
    specs: { type: 'Continuous', rpm: '10,000–15,000', throughput: '10–50 L/h', output: '15–25% solids pellet' },
    vendor: 'Alfa Laval / GEA',
    costRange: '$15K–$40K',
    status: 'maintenance',
    hoursRunning: 4200,
    efficiency: 88,
  },
  {
    id: 'eq-spray-dryer',
    name: 'Spray Dryer',
    category: 'downstream',
    zoneId: 'zone-b-downstream',
    specs: { inletTemp: '175°C', outletTemp: '70–80°C', product: 'Wettable Powder (WP)' },
    vendor: 'Büchi / Chinese',
    costRange: '$20K–$50K',
    status: 'idle',
    hoursRunning: 1800,
    efficiency: 92,
  },
  {
    id: 'eq-freeze-dryer',
    name: 'Freeze Dryer',
    category: 'downstream',
    zoneId: 'zone-b-downstream',
    specs: { temp: '-40°C', shelf: '0.5 m²', cycle: '48–72h', note: 'Higher viability than spray dry' },
    vendor: 'Labconco / Telstar',
    costRange: '$15K–$30K',
    status: 'offline',
    hoursRunning: 600,
    efficiency: 95,
  },
  // Formulation
  {
    id: 'eq-mixing-tank',
    name: 'Formulation Mixing Tank',
    category: 'formulation',
    zoneId: 'zone-c-formulation',
    specs: { volume: '500L', type: 'Jacketed', rpm: '200–400', temp: '20–25°C' },
    vendor: 'Chinese vendors',
    costRange: '$10K–$25K',
    status: 'running',
    hoursRunning: 3200,
    efficiency: 93,
  },
  {
    id: 'eq-homogenizer',
    name: 'High-Shear Homogenizer',
    category: 'formulation',
    zoneId: 'zone-c-formulation',
    specs: { rpm: '3000–5000', particleSize: '<10 µm', duration: '5–15 min' },
    vendor: 'IKA / Silverson',
    costRange: '$5K–$15K',
    status: 'running',
    hoursRunning: 2800,
    efficiency: 90,
  },
  {
    id: 'eq-filling',
    name: 'Auto Filling Machine',
    category: 'packaging',
    zoneId: 'zone-c-formulation',
    specs: { sizes: '100g / 500g / 1kg', type: 'Automatic' },
    vendor: 'Chinese vendors',
    costRange: '$10K–$25K',
    status: 'running',
    hoursRunning: 4100,
    efficiency: 96,
  },
  {
    id: 'eq-sealer',
    name: 'Heat Sealing Machine',
    category: 'packaging',
    zoneId: 'zone-c-formulation',
    specs: { type: 'Heat seal', automation: 'Automatic' },
    vendor: 'Chinese vendors',
    costRange: '$3K–$8K',
    status: 'running',
    hoursRunning: 4100,
    efficiency: 98,
  },
  {
    id: 'eq-labeler',
    name: 'Labeling Machine',
    category: 'packaging',
    zoneId: 'zone-c-formulation',
    specs: { type: 'Wrap-around', automation: 'Automatic' },
    vendor: 'Chinese vendors',
    costRange: '$3K–$8K',
    status: 'running',
    hoursRunning: 4100,
    efficiency: 97,
  },
  // Utilities
  {
    id: 'eq-boiler',
    name: 'Clean Steam Generator / Boiler',
    category: 'utilities',
    zoneId: 'zone-f-utilities',
    specs: { type: 'Electric', pressure: '2–3 bar', output: '100–500 kg/h' },
    vendor: 'Chinese vendors',
    costRange: '$10K–$25K',
    status: 'running',
    hoursRunning: 8760,
    efficiency: 94,
  },
  {
    id: 'eq-chiller',
    name: 'Chiller',
    category: 'utilities',
    zoneId: 'zone-f-utilities',
    specs: { capacity: '5–10 kW', output: '7°C', coolingRate: '1–2°C/min' },
    vendor: 'Carrier / Chinese',
    costRange: '$5K–$15K',
    status: 'running',
    hoursRunning: 8760,
    efficiency: 91,
  },
  {
    id: 'eq-compressor',
    name: 'Oil-Free Air Compressor',
    category: 'utilities',
    zoneId: 'zone-f-utilities',
    specs: { type: 'Oil-free, dry', pressure: '6–8 bar', flow: '500 L/min' },
    vendor: 'Atlas Copco',
    costRange: '$3K–$8K',
    status: 'running',
    hoursRunning: 8760,
    efficiency: 95,
  },
  {
    id: 'eq-water-purif',
    name: 'Water Purification System',
    category: 'utilities',
    zoneId: 'zone-f-utilities',
    specs: { type: 'PW + WFI capability', capacity: '1000 L/day' },
    vendor: 'Local suppliers',
    costRange: '$15K–$30K',
    status: 'running',
    hoursRunning: 8760,
    efficiency: 97,
  },
];

// ============================================================
// MATERIALS — Real Bt fermentation media + formulation
// Sources: URS, BT-PRODUCTION-BRIEF, published literature
// ============================================================

export const materials: Material[] = [
  // === SEED MEDIUM (from BT-PRODUCTION-BRIEF) ===
  { id: 'mat-starch', name: 'Starch', function: 'Carbon source (seed)', usagePercentMin: 30, usagePercentMax: 30, supplier: 'Local', pricePerKg: 0.50, currency: 'USD', stockLevel: 500, reorderPoint: 100, unit: 'g/L' },
  { id: 'mat-soy-flour', name: 'Soybean Meal / Soya Flour', function: 'Carbon + Nitrogen source', usagePercentMin: 30, usagePercentMax: 30, supplier: 'Local / Multiple', pricePerKg: 0.80, currency: 'USD', stockLevel: 500, reorderPoint: 100, unit: 'g/L' },
  { id: 'mat-nacl', name: 'NaCl', function: 'Osmotic balance', usagePercentMin: 9, usagePercentMax: 9, supplier: 'Local', pricePerKg: 0.09, currency: 'USD', stockLevel: 1000, reorderPoint: 200, unit: 'g/L' },
  { id: 'mat-k2hpo4', name: 'K₂HPO₄', function: 'Buffer (base)', usagePercentMin: 0.5, usagePercentMax: 1, supplier: 'Local', pricePerKg: 2.50, currency: 'USD', stockLevel: 100, reorderPoint: 20, unit: 'g/L' },
  { id: 'mat-kh2po4', name: 'KH₂PO₄', function: 'Buffer (acid)', usagePercentMin: 0.5, usagePercentMax: 1, supplier: 'Local', pricePerKg: 2.80, currency: 'USD', stockLevel: 100, reorderPoint: 20, unit: 'g/L' },
  { id: 'mat-mgso4', name: 'MgSO₄·7H₂O', function: 'Mineral cofactor', usagePercentMin: 0.05, usagePercentMax: 0.1, supplier: 'Local', pricePerKg: 1.20, currency: 'USD', stockLevel: 50, reorderPoint: 10, unit: 'g/L' },
  { id: 'mat-fecl3', name: 'FeCl₃', function: 'Trace mineral', usagePercentMin: 0.01, usagePercentMax: 0.05, supplier: 'Local', pricePerKg: 5.00, currency: 'USD', stockLevel: 10, reorderPoint: 3, unit: 'g/L' },
  { id: 'mat-mnso4', name: 'MnSO₄·H₂O', function: 'Trace mineral', usagePercentMin: 0.01, usagePercentMax: 0.05, supplier: 'Local', pricePerKg: 3.00, currency: 'USD', stockLevel: 10, reorderPoint: 3, unit: 'g/L' },
  // === PRODUCTION MEDIUM (same base, industrial scale) ===
  { id: 'mat-glucose', name: 'Glucose', function: 'Supplemental carbon (fed-batch feed)', usagePercentMin: 50, usagePercentMax: 60, supplier: 'Local', pricePerKg: 0.60, currency: 'USD', stockLevel: 300, reorderPoint: 80, unit: 'g/L (feed conc.)' },
  { id: 'mat-corn-steep', name: 'Corn Steep Liquor', function: 'Nitrogen/vitamin supplement', usagePercentMin: 1, usagePercentMax: 3, supplier: 'Multiple', pricePerKg: 0.50, currency: 'USD', stockLevel: 200, reorderPoint: 50, unit: 'g/L' },
  // === CONTROL CHEMICALS (from URS) ===
  { id: 'mat-hcl', name: 'HCl (1M)', function: 'pH down (acid)', usagePercentMin: 0.1, usagePercentMax: 0.5, supplier: 'Local', pricePerKg: 1.50, currency: 'USD', stockLevel: 50, reorderPoint: 10, unit: 'L' },
  { id: 'mat-naoh', name: 'NaOH (1M)', function: 'pH up (base)', usagePercentMin: 0.1, usagePercentMax: 0.5, supplier: 'Local', pricePerKg: 1.00, currency: 'USD', stockLevel: 50, reorderPoint: 10, unit: 'L' },
  { id: 'mat-antifoam', name: 'Antifoam 204 (polyether)', function: 'Foam control — prefer polyether over silicone', usagePercentMin: 0.1, usagePercentMax: 0.5, supplier: 'Sigma-Aldrich / Multiple', pricePerKg: 15.00, currency: 'USD', stockLevel: 20, reorderPoint: 5, unit: 'L' },
  // === WP FORMULATION COMPONENTS ===
  { id: 'mat-sipernat', name: 'SIPERNAT® 22 S', function: 'Skeleton / Carrier', usagePercentMin: 5, usagePercentMax: 15, supplier: 'Evonik (Germany)', pricePerKg: 0.44, currency: 'USD', stockLevel: 500, reorderPoint: 100, unit: 'kg' },
  { id: 'mat-mono-glycol', name: 'Monopropylene Glycol', function: 'Anti-freeze / Co-solvent', usagePercentMin: 5, usagePercentMax: 10, supplier: 'Multiple', pricePerKg: 0.99, currency: 'USD', stockLevel: 300, reorderPoint: 80, unit: 'kg' },
  { id: 'mat-unitop-fl', name: 'Unitop-FL', function: 'Suspending / Wetting', usagePercentMin: 1, usagePercentMax: 3, supplier: 'Rossari Biotech (India)', pricePerKg: 10.0, currency: 'USD', stockLevel: 50, reorderPoint: 20, unit: 'kg' },
  { id: 'mat-unitop-203', name: 'Unitop-203', function: 'Dispersing Agent', usagePercentMin: 1, usagePercentMax: 3, supplier: 'Unitop Chemicals (India)', pricePerKg: 12.0, currency: 'USD', stockLevel: 50, reorderPoint: 20, unit: 'kg' },
  { id: 'mat-unitop-mso', name: 'Unitop-MSO', function: 'Rain-fastness Adjuvant', usagePercentMin: 2, usagePercentMax: 5, supplier: 'Rossari Biotech (India)', pricePerKg: 14.0, currency: 'USD', stockLevel: 40, reorderPoint: 15, unit: 'kg' },
  { id: 'mat-xanthan', name: 'Xanthan Gum', function: 'Thickener / Suspending', usagePercentMin: 0.5, usagePercentMax: 2, supplier: 'Multiple', pricePerKg: 4.75, currency: 'USD', stockLevel: 100, reorderPoint: 30, unit: 'kg' },
  { id: 'mat-sucrose', name: 'Sucrose', function: 'UV Protectant', usagePercentMin: 2, usagePercentMax: 5, supplier: 'Local', pricePerKg: 0.45, currency: 'USD', stockLevel: 400, reorderPoint: 100, unit: 'kg' },
  { id: 'mat-bht', name: 'BHT', function: 'Antioxidant', usagePercentMin: 0.01, usagePercentMax: 0.1, supplier: 'Multiple', pricePerKg: 7.0, currency: 'USD', stockLevel: 20, reorderPoint: 5, unit: 'kg' },
];

export const bomEntries: BOMEntry[] = materials.map(m => ({
  id: `bom-${m.id}`,
  productId: 'prod-bt-wp',
  materialId: m.id,
  materialName: m.name,
  percentMin: m.usagePercentMin,
  percentMax: m.usagePercentMax,
  percentMid: (m.usagePercentMin + m.usagePercentMax) / 2,
  function: m.function,
  supplier: m.supplier,
  costPerKg: m.pricePerKg,
}));

// ============================================================
// BATCHES — Real Bt batch tracking with QC
// ============================================================

export const batches: Batch[] = [
  {
    id: 'BTH-2026-001',
    product: 'Bt Biopesticide WP',
    size: 50,
    status: 'in_progress',
    startDate: '2026-04-18',
    estimatedCompletion: '2026-04-25',
    currentStage: 'Fermentation (50L)',
    equipmentUsed: ['eq-prod-br-50', 'eq-media-prep'],
    qcResults: [],
    materials: [
      { materialId: 'mat-starch', name: 'Starch', plannedAmount: 1.5, actualAmount: 0, unit: 'kg' },
      { materialId: 'mat-soy-flour', name: 'Soybean Meal', plannedAmount: 1.5, actualAmount: 0, unit: 'kg' },
      { materialId: 'mat-nacl', name: 'NaCl', plannedAmount: 0.45, actualAmount: 0, unit: 'kg' },
    ],
    notes: 'Fed-batch mode. Two-feed strategy: glucose feed at 10h and 20h. DO ≥30%, pH 7.0, 30°C, 400-600 rpm. Target 48-72h run.',
  },
  {
    id: 'BTH-2026-002',
    product: 'Bt Biopesticide WP',
    size: 50,
    status: 'qc_pending',
    startDate: '2026-04-15',
    estimatedCompletion: '2026-04-22',
    currentStage: 'QC Testing',
    equipmentUsed: ['eq-mixing-tank', 'eq-homogenizer', 'eq-filling'],
    qcResults: [
      { id: 'qc-1', batchId: 'BTH-2026-002', testName: 'Spore Count (CFU/g)', targetValue: '≥1×10⁹', actualValue: '2.3×10⁹', unit: 'CFU/g', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-21T09:00:00Z', notes: 'FAO/WHO minimum: 1×10⁹ CFU/g' },
      { id: 'qc-2', batchId: 'BTH-2026-002', testName: 'pH', targetValue: '6.5–7.5', actualValue: '7.1', unit: 'pH', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-21T09:15:00Z' },
      { id: 'qc-3', batchId: 'BTH-2026-002', testName: 'Suspensibility', targetValue: '≥60%', actualValue: '78%', unit: '%', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-21T09:30:00Z', notes: 'FAO/WHO: ≥60% for WP' },
      { id: 'qc-4', batchId: 'BTH-2026-002', testName: 'Wetting Time', targetValue: '≤120 sec', actualValue: '42', unit: 'sec', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-21T09:45:00Z' },
      { id: 'qc-5', batchId: 'BTH-2026-002', testName: 'Moisture Content', targetValue: '≤8%', actualValue: '6.2', unit: '%', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-21T10:00:00Z' },
      { id: 'qc-6', batchId: 'BTH-2026-002', testName: 'Particle Size (<75µm)', targetValue: '≥98% pass', actualValue: '99.1%', unit: '%', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-21T10:15:00Z' },
      { id: 'qc-7', batchId: 'BTH-2026-002', testName: 'Entomotoxicity (SBU/mL)', targetValue: '≥15×10⁶', actualValue: '18.5×10⁶', unit: 'SBU/mL', result: 'pass', testedBy: 'Dr. Fatima', testedAt: '2026-04-21T11:00:00Z', notes: 'Bioassay against S. litura 3rd instar' },
      { id: 'qc-8', batchId: 'BTH-2026-002', testName: 'Contamination Check', targetValue: 'No human pathogens', actualValue: 'Negative', unit: '—', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-21T10:30:00Z', notes: 'Gram stain + selective media' },
    ],
    materials: [
      { materialId: 'mat-sipernat', name: 'SIPERNAT® 22 S', plannedAmount: 10, actualAmount: 10.2, unit: 'kg' },
      { materialId: 'mat-mono-glycol', name: 'Monopropylene Glycol', plannedAmount: 7, actualAmount: 6.8, unit: 'kg' },
      { materialId: 'mat-unitop-fl', name: 'Unitop-FL', plannedAmount: 2, actualAmount: 2.1, unit: 'kg' },
      { materialId: 'mat-unitop-mso', name: 'Unitop-MSO', plannedAmount: 3, actualAmount: 3.0, unit: 'kg' },
    ],
    yield: 94.2,
    notes: 'Full WP formulation run — awaiting final bioassay confirmation. Fed-batch 2-feed process.',
  },
  {
    id: 'BTH-2026-003',
    product: 'Bt Biopesticide WP',
    size: 50,
    status: 'released',
    startDate: '2026-04-10',
    estimatedCompletion: '2026-04-17',
    currentStage: 'Complete',
    equipmentUsed: ['eq-prod-br-50', 'eq-centrifuge', 'eq-spray-dryer', 'eq-mixing-tank', 'eq-homogenizer', 'eq-filling'],
    qcResults: [
      { id: 'qc-10', batchId: 'BTH-2026-003', testName: 'Spore Count (CFU/g)', targetValue: '≥1×10⁹', actualValue: '3.1×10⁹', unit: 'CFU/g', result: 'pass', testedBy: 'Dr. Ahmed', testedAt: '2026-04-17T09:00:00Z' },
      { id: 'qc-11', batchId: 'BTH-2026-003', testName: 'Entomotoxicity (SBU/mL)', targetValue: '≥15×10⁶', actualValue: '22.1×10⁶', unit: 'SBU/mL', result: 'pass', testedBy: 'Dr. Fatima', testedAt: '2026-04-17T14:00:00Z' },
    ],
    materials: [],
    yield: 97.1,
    notes: 'First validated batch — 30 units dispatched. Dry mass yield: 4.2 g/L (wet: ~16.8 g/L pre-centrifuge)',
  },
  {
    id: 'BTH-2026-004',
    product: 'Bt Biopesticide WP',
    size: 50,
    status: 'queued',
    startDate: '2026-04-26',
    estimatedCompletion: '2026-05-03',
    currentStage: 'Queued — Media Prep',
    equipmentUsed: [],
    qcResults: [],
    materials: [],
    notes: 'Scheduled after BTH-2026-001 completes',
  },
];

// ============================================================
// PROCESS STAGES — Real Bt parameters from literature + URS
// Sources: Vu et al. 2010, Malairuang et al. 2023, URS questionnaire
// ============================================================

export const processStages: ProcessStage[] = [
  { id: 'ps-mcb', name: 'Master Cell Bank', zone: 'upstream', description: 'Frozen stock (-80°C), Btk HD-1 strain, accession number required per FAO/WHO' },
  { id: 'ps-wcb', name: 'Working Cell Bank', zone: 'upstream', description: 'Aliquots from MCB (-80°C)' },
  {
    id: 'ps-seed', name: 'Seed Bioreactor',
    zone: 'upstream',
    description: 'Seed medium: Starch 30 g/L + Soya flour 30 g/L + NaCl 9 g/L + buffer',
    duration: '24h',
    equipment: ['eq-seed-br'],
    parameters: { temp: '37°C', pH: '7.0', rpm: '220', volume: '2–5L', medium: 'Seed (starch+soya)' },
  },
  {
    id: 'ps-prod', name: 'Production Bioreactor',
    zone: 'upstream',
    description: 'Fed-batch: glucose feed at 10h + 20h (2-feed max to avoid Spo- variants). DO ≥30%. Harvest at 48h (spore peak) or 72h (endotoxin peak).',
    duration: '48–72h',
    equipment: ['eq-prod-br-50'],
    parameters: {
      mode: 'Fed-batch (2 feeds)',
      temp: '30°C',
      pH: '7.0 (±0.1)',
      DO: '≥30% sat (cascade: agitation 100-600 rpm → gas flow 3-5 VVM → O₂ enrich 40% max)',
      rpm: '100–800 (3× Rushton impellers)',
      aeration: '0.5–2.0 VVM air, 0–0.5 VVM O₂',
      feed: 'Glucose 50-60 g/L, 2 additions at 10h and 20h',
      feedTrigger: 'Time-based (not DO or glucose depletion)',
      antifoam: 'Polyether-based (Antifoam 204), automated dosing',
      harvestPoint: '48h (spore peak) or when endotoxin plateaus at ~48-72h',
      yield: '~4 g/L dry mass (16-20 g/L wet biomass pre-centrifuge)',
    },
  },
  { id: 'ps-harvest', name: 'Harvest — Centrifugation', zone: 'downstream', description: 'Disc stack centrifuge, 10K–15K rpm. Pellet: 15–25% solids. Hold time <4h before formulation.', equipment: ['eq-centrifuge'] },
  { id: 'ps-dry', name: 'Drying', zone: 'downstream', description: 'Spray dry (WP, 175°C in / 70-80°C out) or freeze dry (higher viability, -40°C, 48-72h)', equipment: ['eq-spray-dryer', 'eq-freeze-dryer'] },
  { id: 'ps-mix', name: 'Formulation Mixing', zone: 'formulation', description: 'Add carrier (SIPERNAT), dispersants, adjuvants per BOM. 30–60 min', duration: '30–60 min', equipment: ['eq-mixing-tank'] },
  { id: 'ps-homo', name: 'Homogenization', zone: 'formulation', description: 'High-shear, 3000–5000 rpm, particle <75µm (≥98% pass)', duration: '5–15 min', equipment: ['eq-homogenizer'] },
  {
    id: 'ps-qc1', name: 'QC Checkpoint 1',
    zone: 'qc',
    description: 'Spore count (≥1×10⁹ CFU/g), pH (6.5–7.5), suspensibility (≥60%), moisture (≤8%), particle size, wetting time',
    qcRequired: true,
    parameters: {
      sporeCount: '≥1×10⁹ CFU/g (FAO/WHO minimum)',
      pH: '6.5–7.5',
      suspensibility: '≥60% (CIPAC MT 15, FAO/WHO)',
      moisture: '≤8%',
      particleSize: '≥98% pass 75µm sieve',
      wettingTime: '≤120 sec',
    },
  },
  { id: 'ps-fill', name: 'Filling', zone: 'packaging', description: 'Auto filling — 100g/500g/1kg', equipment: ['eq-filling'] },
  { id: 'ps-seal', name: 'Sealing', zone: 'packaging', description: 'Heat seal, automatic', equipment: ['eq-sealer'] },
  { id: 'ps-label', name: 'Labeling', zone: 'packaging', description: 'Batch #, expiry (≥2 year shelf life), registration', equipment: ['eq-labeler'] },
  {
    id: 'ps-qc2', name: 'QC Final Release',
    zone: 'qc',
    description: 'Entomotoxicity (≥15×10⁶ SBU/mL), contamination check (no human pathogens), stability sample, batch release',
    qcRequired: true,
    parameters: {
      entomotoxicity: '≥15×10⁶ SBU/mL (bioassay vs S. litura or target pest)',
      contamination: 'No human pathogens (Gram stain + selective media)',
      deltaEndotoxin: '≥1.0 g/L (HPLC)',
      stability: 'Sample for accelerated storage (40°C/75% RH)',
      shelfLife: '≥2 years (FAO/WHO)',
    },
  },
  { id: 'ps-store', name: 'Cold Storage', zone: 'warehouse', description: '4–8°C, batch record filed' },
  { id: 'ps-dispatch', name: 'Dispatch', zone: 'warehouse', description: 'Ship to market — GCC / MENA' },
];

// ============================================================
// TRANSFER GATES
// ============================================================

export const transferGates: TransferGate[] = [
  { id: 'G0', name: 'MOU Execution', status: 'completed', description: 'Partnership agreement signed' },
  { id: 'G1', name: 'Bioreactor Procurement', status: 'in_progress', description: '50L: Lab1st $39-44K. 500L: pending. Lean total: $50-80K. Standard: $80-120K. Premium: $150-250K.' },
  { id: 'G2', name: 'Facility Preparation', status: 'pending', description: 'ISO 8, 380V/3Φ, 6-8 bar oil-free air, PW/WFI, 2-3 bar steam (100-500 kg/h)', dependencies: ['G1'] },
  { id: 'G3', name: 'Pilot Validation (50L)', status: 'pending', description: 'First successful 50L fed-batch. IQ/OQ/PQ. 3 consecutive validated batches.', dependencies: ['G1', 'G2'] },
  { id: 'G4', name: 'Scale-Up (500L)', status: 'pending', description: 'Geometric similarity confirmed. Constant kLa strategy. 2-feed fed-batch.', dependencies: ['G3'] },
  { id: 'G5', name: 'Process Validation (3 runs)', status: 'pending', description: '3 consecutive validated batches at 500L. ≥1×10⁹ CFU/g, ≥15×10⁶ SBU/mL.', dependencies: ['G4'] },
  { id: 'G6', name: 'Regulatory Submission', status: 'pending', description: 'MEWA/EPA dossier. FAO/WHO spec compliance. Strain accession number.', dependencies: ['G5'] },
  { id: 'G7', name: 'First Commercial Batch', status: 'pending', description: 'Market-ready production', dependencies: ['G6'] },
  { id: 'G8', name: 'Market Launch — GCC/MENA', status: 'pending', description: 'Commercial distribution', dependencies: ['G7'] },
];

// ============================================================
// ORDERS
// ============================================================

export const orders: Order[] = [
  { id: 'ORD-001', customer: 'Ministry of Agriculture — Riyadh', product: 'Bt Biopesticide WP', quantity: 500, unit: '1L bottles', status: 'pending', orderDate: '2026-04-15' },
  { id: 'ORD-002', customer: 'Al Rajhi Farms', product: 'Bt Biopesticide WP', quantity: 50, unit: '500g bottles', status: 'processing', orderDate: '2026-04-18' },
  { id: 'ORD-003', customer: 'Delta Distributors', product: 'Bt Biopesticide WP', quantity: 2000, unit: '100g sachets', status: 'pending', orderDate: '2026-04-20' },
];
