/**
 * Upstream Fermentation Zone — P&ID Data
 * 
 * Equipment train: Seed BR (10L) → Production BR (50L) → Production BR (500L)
 * With: media prep, autoclave, air supply, CIP, cooling
 * 
 * Drawing: PA-PID-USP-001 Rev. A
 */

import type { ZonePIDData } from '@/types/pid-zone';

export const upstreamPID: ZonePIDData = {
  zoneId: 'z-upstream',
  zoneName: 'Upstream Fermentation',
  zoneType: 'upstream',
  isoClass: 'ISO 8',
  drawingNumber: 'PA-PID-USP-001',
  revision: 'Rev. A',

  viewBox: { x: 0, y: 0, width: 800, height: 520 },

  equipment: [
    // Seed Bioreactor 10L
    {
      id: 'BR-SEED-01',
      symbolId: 'bioreactor',
      name: 'Seed Fermenter 10L',
      tag: 'BR-001',
      x: 80, y: 60,
      width: 60, height: 70,
      rotation: 0,
      vendor: 'Eppendorf',
      model: 'BioFlo 310',
      specs: { volume: '10L', type: 'Stirred-tank', jacket: 'Single' },
      zone: 'z-upstream',
    },
    // Production Bioreactor 50L
    {
      id: 'BR-50L-01',
      symbolId: 'bioreactor',
      name: 'Production Bioreactor 50L',
      tag: 'BR-002',
      x: 280, y: 60,
      width: 70, height: 80,
      rotation: 0,
      vendor: 'Eppendorf',
      model: 'BioFlo 310',
      specs: { volume: '50L', type: 'Stirred-tank', jacket: 'Dual', impeller: 'Rushton' },
      zone: 'z-upstream',
    },
    // Production Bioreactor 500L
    {
      id: 'BR-500L-01',
      symbolId: 'bioreactor',
      name: 'Production Bioreactor 500L',
      tag: 'BR-003',
      x: 500, y: 40,
      width: 80, height: 95,
      rotation: 0,
      vendor: 'Eppendorf',
      model: 'BioFlo 610',
      specs: { volume: '500L', type: 'Stirred-tank', jacket: 'Dual', impeller: 'Rushton + Marine' },
      zone: 'z-upstream',
    },
    // Media Prep Tank
    {
      id: 'TK-MEDIA-01',
      symbolId: 'mixing-tank',
      name: 'Media Preparation Tank',
      tag: 'TK-001',
      x: 80, y: 260,
      width: 60, height: 65,
      rotation: 0,
      vendor: 'Lab1st',
      specs: { volume: '200L', heating: 'Electric', agitation: 'Top-entry' },
      zone: 'z-upstream',
    },
    // Autoclave
    {
      id: 'E-AUTOCLAVE-01',
      symbolId: 'boiler',
      name: 'Autoclave ST-200',
      tag: 'B-001',
      x: 280, y: 270,
      width: 55, height: 50,
      rotation: 0,
      vendor: 'Tuttnauer',
      model: 'ST-200',
      specs: { volume: '200L', temp: '121°C', pressure: '1.2 bar' },
      zone: 'z-upstream',
    },
    // WFI Point of Use
    {
      id: 'TK-WFI-01',
      symbolId: 'tank-vertical',
      name: 'WFI Hold Tank',
      tag: 'TK-002',
      x: 440, y: 260,
      width: 50, height: 60,
      rotation: 0,
      specs: { volume: '500L', temp: '80°C (hot hold)', material: 'SS316L' },
      zone: 'z-upstream',
    },
    // Air Compressor (off-drawing reference)
    {
      id: 'K-AIR-01',
      symbolId: 'compressor',
      name: 'Oil-Free Air Compressor',
      tag: 'K-001',
      x: 650, y: 80,
      width: 50, height: 45,
      rotation: 0,
      specs: { type: 'Oil-free', pressure: '7 bar', flow: '500 L/min' },
      zone: 'z-upstream',
    },
    // Chiller (off-drawing reference)
    {
      id: 'CH-001',
      symbolId: 'chiller',
      name: 'Process Chiller',
      tag: 'CH-001',
      x: 650, y: 170,
      width: 50, height: 45,
      rotation: 0,
      specs: { capacity: '15 kW', temp: '4-12°C', refrigerant: 'R410A' },
      zone: 'z-upstream',
    },
  ],

  connections: [
    // Media Prep → Seed BR
    {
      id: 'C-001',
      lineType: 'process',
      from: { equipmentId: 'TK-MEDIA-01', portId: 'outlet' },
      to: { equipmentId: 'BR-SEED-01', portId: 'inlet' },
      points: [
        { x: 110, y: 260 },
        { x: 110, y: 200 },
        { x: 110, y: 130 },
      ],
      diameter: 'DN25',
      material: 'SS316L',
      label: 'Sterilized Media',
    },
    // Seed BR → 50L BR (inoculation)
    {
      id: 'C-002',
      lineType: 'process',
      from: { equipmentId: 'BR-SEED-01', portId: 'outlet' },
      to: { equipmentId: 'BR-50L-01', portId: 'inlet' },
      points: [
        { x: 140, y: 130 },
        { x: 200, y: 130 },
        { x: 200, y: 100 },
        { x: 280, y: 100 },
      ],
      diameter: 'DN25',
      material: 'Silicone',
      label: 'Inoculum Transfer',
    },
    // 50L BR → 500L BR
    {
      id: 'C-003',
      lineType: 'process',
      from: { equipmentId: 'BR-50L-01', portId: 'outlet' },
      to: { equipmentId: 'BR-500L-01', portId: 'inlet' },
      points: [
        { x: 350, y: 140 },
        { x: 420, y: 140 },
        { x: 420, y: 100 },
        { x: 500, y: 100 },
      ],
      diameter: 'DN50',
      material: 'SS316L',
      label: 'Scale-up Transfer',
    },
    // Air supply → 500L BR
    {
      id: 'C-004',
      lineType: 'instrument',
      from: { equipmentId: 'K-AIR-01', portId: 'outlet' },
      to: { equipmentId: 'BR-500L-01', portId: 'inlet' },
      points: [
        { x: 650, y: 100 },
        { x: 600, y: 100 },
        { x: 580, y: 80 },
        { x: 550, y: 80 },
      ],
      diameter: 'DN25',
      label: 'Sterile Air',
    },
    // Chiller → 500L BR jacket
    {
      id: 'C-005',
      lineType: 'utility',
      from: { equipmentId: 'CH-001', portId: 'outlet' },
      to: { equipmentId: 'BR-500L-01', portId: 'jacket-in' },
      points: [
        { x: 650, y: 190 },
        { x: 600, y: 190 },
        { x: 600, y: 130 },
        { x: 580, y: 130 },
      ],
      diameter: 'DN25',
      label: 'Chilled Water',
    },
    // WFI → Media Prep
    {
      id: 'C-006',
      lineType: 'process',
      from: { equipmentId: 'TK-WFI-01', portId: 'outlet' },
      to: { equipmentId: 'TK-MEDIA-01', portId: 'inlet' },
      points: [
        { x: 465, y: 260 },
        { x: 465, y: 230 },
        { x: 140, y: 230 },
        { x: 140, y: 260 },
      ],
      diameter: 'DN25',
      material: 'SS316L',
      label: 'WFI',
    },
    // Autoclave steam supply (simplified)
    {
      id: 'C-007',
      lineType: 'steam',
      from: { equipmentId: 'E-AUTOCLAVE-01', portId: 'inlet' },
      to: { equipmentId: 'BR-50L-01', portId: 'inlet' },
      points: [
        { x: 310, y: 270 },
        { x: 310, y: 200 },
        { x: 310, y: 140 },
      ],
      diameter: 'DN15',
      label: 'Clean Steam (SIP)',
    },
    // 500L harvest → downstream (off-zone)
    {
      id: 'C-008',
      lineType: 'process',
      from: { equipmentId: 'BR-500L-01', portId: 'outlet' },
      to: { equipmentId: 'EXT-DOWNSTREAM', portId: 'inlet' },
      points: [
        { x: 540, y: 135 },
        { x: 600, y: 135 },
        { x: 750, y: 135 },
      ],
      diameter: 'DN50',
      material: 'SS316L',
      label: 'Broth → Centrifuge',
    },
  ],

  instruments: [
    // Seed BR instruments
    {
      id: 'TT-001',
      symbolId: 'sensor-temp',
      tag: 'TT-001',
      variable: 'Temperature',
      function: 'Transmitter',
      loopNumber: 1,
      mountedOn: 'BR-SEED-01',
      x: 60, y: 90,
      range: '0-50°C',
      signal: '4-20mA',
    },
    {
      id: 'AIC-001',
      symbolId: 'sensor-ph',
      tag: 'AIC-001',
      variable: 'pH',
      function: 'Indicating Controller',
      loopNumber: 1,
      mountedOn: 'BR-SEED-01',
      x: 60, y: 115,
      range: '0-14 pH',
      signal: '4-20mA',
    },
    {
      id: 'AIC-002',
      symbolId: 'sensor-do',
      tag: 'AIC-002',
      variable: 'Dissolved Oxygen',
      function: 'Indicating Controller',
      loopNumber: 2,
      mountedOn: 'BR-SEED-01',
      x: 60, y: 140,
      range: '0-100% DO',
      signal: '4-20mA',
    },
    // 50L BR instruments
    {
      id: 'TIC-001',
      symbolId: 'sensor-temp',
      tag: 'TIC-001',
      variable: 'Temperature',
      function: 'Indicating Controller',
      loopNumber: 10,
      mountedOn: 'BR-50L-01',
      x: 260, y: 80,
      range: '0-50°C',
      signal: '4-20mA',
    },
    {
      id: 'PI-001',
      symbolId: 'sensor-pressure',
      tag: 'PI-001',
      variable: 'Pressure',
      function: 'Indicator',
      loopNumber: 11,
      mountedOn: 'BR-50L-01',
      x: 260, y: 105,
      range: '0-2 bar',
    },
    {
      id: 'FI-001',
      symbolId: 'sensor-flow',
      tag: 'FI-001',
      variable: 'Air Flow',
      function: 'Indicator',
      loopNumber: 12,
      mountedOn: 'BR-50L-01',
      x: 260, y: 130,
      range: '0-20 L/min',
    },
    // 500L BR instruments
    {
      id: 'TIC-002',
      symbolId: 'sensor-temp',
      tag: 'TIC-002',
      variable: 'Temperature',
      function: 'Indicating Controller',
      loopNumber: 20,
      mountedOn: 'BR-500L-01',
      x: 480, y: 60,
      range: '0-50°C',
      signal: '4-20mA',
    },
    {
      id: 'AIC-003',
      symbolId: 'sensor-ph',
      tag: 'AIC-003',
      variable: 'pH',
      function: 'Indicating Controller',
      loopNumber: 21,
      mountedOn: 'BR-500L-01',
      x: 480, y: 85,
      range: '0-14 pH',
      signal: '4-20mA',
    },
    {
      id: 'AIC-004',
      symbolId: 'sensor-do',
      tag: 'AIC-004',
      variable: 'Dissolved Oxygen',
      function: 'Indicating Controller',
      loopNumber: 22,
      mountedOn: 'BR-500L-01',
      x: 480, y: 110,
      range: '0-100% DO',
      signal: '4-20mA',
    },
    {
      id: 'FI-002',
      symbolId: 'sensor-flow',
      tag: 'FI-002',
      variable: 'Media Feed',
      function: 'Indicator',
      loopNumber: 23,
      mountedOn: 'BR-500L-01',
      x: 480, y: 135,
      range: '0-50 L/min',
    },
    // Media Prep instruments
    {
      id: 'LI-001',
      symbolId: 'sensor-level',
      tag: 'LI-001',
      variable: 'Level',
      function: 'Indicator',
      loopNumber: 30,
      mountedOn: 'TK-MEDIA-01',
      x: 60, y: 290,
      range: '0-100%',
    },
    {
      id: 'TT-003',
      symbolId: 'sensor-temp',
      tag: 'TT-003',
      variable: 'Temperature',
      function: 'Transmitter',
      loopNumber: 31,
      mountedOn: 'TK-MEDIA-01',
      x: 60, y: 315,
      range: '0-150°C',
    },
  ],

  controlLoops: [
    {
      id: 'CL-TEMP-01',
      tag: 'TIC-001',
      name: '50L Reactor Temperature',
      type: 'single',
      measuredVariable: 'Temperature',
      setpoint: '30°C',
      output: 'Jacket cooling valve',
      instruments: ['TIC-001'],
      alarmHigh: '35°C',
      alarmLow: '25°C',
    },
    {
      id: 'CL-PH-01',
      tag: 'AIC-001',
      name: 'Seed pH Control',
      type: 'single',
      measuredVariable: 'pH',
      setpoint: '7.0',
      output: 'Acid/Base dosing pumps',
      instruments: ['AIC-001'],
      alarmHigh: '7.5',
      alarmLow: '6.5',
    },
    {
      id: 'CL-DO-01',
      tag: 'AIC-004',
      name: '500L DO Cascade',
      type: 'cascade',
      measuredVariable: 'Dissolved Oxygen',
      setpoint: '30%',
      output: 'Agitation → Air/O₂ valve',
      instruments: ['AIC-004'],
      alarmLow: '20%',
    },
    {
      id: 'CL-FEED-01',
      tag: 'FIC-001',
      name: 'Fed-Batch Feed Control',
      type: 'single',
      measuredVariable: 'Feed Rate',
      setpoint: 'Per growth curve',
      output: 'Feed pump',
      instruments: ['FI-002'],
    },
    {
      id: 'CL-FOAM-01',
      tag: 'AL-001',
      name: 'Anti-Foam Control',
      type: 'single',
      measuredVariable: 'Foam',
      setpoint: 'On/Off',
      output: 'Antifoam pump',
      instruments: [],
    },
  ],

  nozzles: [
    { id: 'N-BR500-HARVEST', equipmentId: 'BR-500L-01', name: 'Harvest Outlet', size: 'DN50', type: 'Tri-clamp', rating: 'BPE', service: 'Broth' },
    { id: 'N-BR500-AIR', equipmentId: 'BR-500L-01', name: 'Sparger', size: 'DN25', type: 'Tri-clamp', rating: 'BPE', service: 'Sterile Air' },
    { id: 'N-TK-MEDIA-IN', equipmentId: 'TK-MEDIA-01', name: 'WFI Inlet', size: 'DN25', type: 'Tri-clamp', rating: 'BPE', service: 'WFI' },
  ],

  // Mock live data
  equipmentStatus: [
    { equipmentId: 'BR-SEED-01', status: 'running', efficiency: 92, hoursRunning: 2400, batchId: 'batch-001' },
    { equipmentId: 'BR-50L-01', status: 'running', efficiency: 94, hoursRunning: 1200, batchId: 'batch-001' },
    { equipmentId: 'BR-500L-01', status: 'idle', efficiency: 100, hoursRunning: 0 },
    { equipmentId: 'TK-MEDIA-01', status: 'running', efficiency: 98, hoursRunning: 3200 },
    { equipmentId: 'E-AUTOCLAVE-01', status: 'running', efficiency: 99, hoursRunning: 5000 },
    { equipmentId: 'TK-WFI-01', status: 'running', efficiency: 97, hoursRunning: 4100 },
    { equipmentId: 'K-AIR-01', status: 'running', efficiency: 95, hoursRunning: 2800 },
    { equipmentId: 'CH-001', status: 'running', efficiency: 96, hoursRunning: 1900 },
  ],

  instrumentValues: [
    { instrumentId: 'TT-001', value: 30.2, unit: '°C', setpoint: 30, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z', trend: [29.8, 30.0, 30.1, 30.2, 30.2, 30.1, 30.2] },
    { instrumentId: 'AIC-001', value: 7.02, unit: 'pH', setpoint: 7.0, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z', trend: [6.98, 7.01, 7.03, 7.02, 7.00, 7.01, 7.02] },
    { instrumentId: 'AIC-002', value: 32, unit: '%', setpoint: 30, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z', trend: [28, 29, 30, 31, 32, 32, 32] },
    { instrumentId: 'TIC-001', value: 30.1, unit: '°C', setpoint: 30, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z', trend: [29.9, 30.0, 30.0, 30.1, 30.1, 30.0, 30.1] },
    { instrumentId: 'PI-001', value: 0.48, unit: 'bar', setpoint: 0.5, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z', trend: [0.47, 0.48, 0.49, 0.48, 0.48, 0.49, 0.48] },
    { instrumentId: 'FI-001', value: 8.5, unit: 'L/min', alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z', trend: [8.2, 8.3, 8.4, 8.5, 8.5, 8.4, 8.5] },
    { instrumentId: 'TIC-002', value: 22, unit: '°C', setpoint: 30, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z' },
    { instrumentId: 'AIC-003', value: 6.8, unit: 'pH', setpoint: 7.0, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z' },
    { instrumentId: 'AIC-004', value: 85, unit: '%', setpoint: 30, alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z' },
    { instrumentId: 'FI-002', value: 0, unit: 'L/min', alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z' },
    { instrumentId: 'LI-001', value: 65, unit: '%', alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z' },
    { instrumentId: 'TT-003', value: 82, unit: '°C', alarmState: 'normal', lastUpdated: '2026-04-22T23:00:00Z' },
  ],

  valvePositions: [
    { valveId: 'V-MEDIA-01', position: 'open', percentOpen: 100, mode: 'auto' },
    { valveId: 'V-AIR-01', position: 'open', percentOpen: 45, mode: 'auto' },
    { valveId: 'V-COOL-01', position: 'partial', percentOpen: 30, mode: 'auto' },
    { valveId: 'V-HARVEST-01', position: 'closed', percentOpen: 0, mode: 'manual' },
  ],

  pipeFlow: [
    { connectionId: 'C-001', flowing: true, flowRate: 2.5, animated: true },
    { connectionId: 'C-002', flowing: true, flowRate: 0.5, animated: true },
    { connectionId: 'C-003', flowing: false, animated: false },
    { connectionId: 'C-004', flowing: true, flowRate: 12, animated: true },
    { connectionId: 'C-005', flowing: true, flowRate: 15, temperature: 8, animated: true },
    { connectionId: 'C-006', flowing: true, flowRate: 5, animated: true },
    { connectionId: 'C-007', flowing: false, animated: false },
    { connectionId: 'C-008', flowing: false, animated: false },
  ],
};
